### PR TITLE
Add CockroachDB style

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
First of a few PRs to start adding styles we archived to test the docs a while back, plus improvements we added, and new styles. We need to improve our own release steps for these, and I have loads more that I'm working through in alphabetical order, just wanted to do one first to see if the style was correct.

### CODE REVIEW

**Comment by jdkato** [comment]
Vale Server relies on Atom feeds to determine when a new version of a style has been released&mdash;GitHub generates these automatically for repositories with tagged releases (e.g., https://github.com/errata-ai/Microsoft/releases.atom). In other words, the `zip` file should be a versioned release artifact, not simply another file checked into the repository.

**Comment by ChrisChinchilla** [comment]
@jdkato Ahh, OK, I was looking into that, will figure it out and reapply.

**Comment by ChrisChinchilla** [comment]
@jdkato How does this work for you? As we have all the styles in sub folders, it's not so ideal for releases, and I have to create them manually with manually generated zip files. In the long run I ca probably automate that, but wanted to see if this suited the project first.

**Comment by jdkato** [comment]
Sorry for not replying -- this issue somehow got away from me. Is this something you're still interested in?

**Pull request closed without merging**
