### PR TITLE
Add CockroachDB to styles list

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
I closed #3 as we restructured our styles library into separate repos for better distribution. I cannot seem to get the correct "latest release" link to work in the  same way that you have and the GitHub docs state, so hopefully this is fine.

More styles to come!

### CODE REVIEW

**Comment by jdkato** [comment]
Linking to `master` works in the sense that it'll always fetch the "latest" files, but there are two problems from Vale Server's perspective:

1. This downloads the *entire* repository instead of just the style `.zip`. This means that we could potentially be installing a lot of unnecessary files (for example, the [Microsoft](https://github.com/errata-ai/Microsoft) style contains almost twice as many files related to testing than the actual style itself). It can also result in error messages if the repository contains unrelated `.yml` files (such as `yamllint.yml`).

2. Since there's no named release asset (i.e., a `CockroachDB.zip` file containing *only* the style files), the style would be installed as `CockroachDB-master`&mdash;meaning, for example, we'd need to write `BasedOnStyles = CockroachDB-master` in a config file.

---

Another issue is that your [`meta.json`](https://github.com/testthedocs/MailChimp/blob/master/meta.json) isn't valid JSON since it contains JS-style comments (`\\`). This was likely due to poor documentation on my part and I'll make sure to update the README with a copy-paste-able example.

---

I know the requirements for this repo are strict, but that's only because it has to support a fully-automated installation process for Vale Server (so even things like `.zip` naming matter). To (hopefully) make it easier, I've made the [`Joblint`](https://github.com/errata-ai/Joblint/blob/master/README.md#using-the-template) style into a [template repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template). So, adding a new style should now only require minor edits.

**Comment by ChrisChinchilla** [comment]
That's fine. I have fixed the meta.json files, but I am still struggling to generate the latest.zip file as mentioned here - https://help.github.com/en/github/administering-a-repository/linking-to-releases

I wonder if it's because we have no sub folders? We don't really need any sub folders to be honest, but I guess we could restructure them if this works.

We did create our own style template, but maybe I'll fork yours now instead.

**Comment by jdkato** [comment]
I think the missing step is the last section in GitHub's docs:

> If you'd like to link directly to a download of your latest release asset you can link to /owner/name/releases/latest/download/asset-name.zip.

All of the styles currently included in this repo include a release asset named `<style>.zip` (e.g., `CockroachDB.zip`). You don't need to have subfolders to create this (although I do think including tests is an important aspect of maintaining a style): You just need to create a `.zip` file and upload it as a release asset. 

The `Joblint` template mentioned above does this automatically whenever a new release is cut:

https://github.com/errata-ai/Joblint/blob/35e9a2d7c9f1a94bb1b26b7f9aaed89fd8d1f69f/.travis.yml#L20-L27

**Comment by ChrisChinchilla** [comment]
Ohh, you're creating the zip and adding it to the release! Not using the default GitHub generated ones! That might make sense. That aside, even that link in the GitHub docs, still doesn't work, no idea why.

I will look into tests at some point, but not quite yet.

So you think that the best approach is to follow some of the similar steps you have above, using a CI to create a zip file (of whatever) and then use that the create the release asset?

If all this works, I'll make a PR to this repo with instructions for people like me :)

**Comment by ChrisChinchilla** [comment]
Hey @jdkato I made a whole bunch of changes to https://github.com/testthedocs/CockroachDB to get this in sync with your template. I noted a few things to add to docs once I got it all working. I'm just wondering if there's a way to automate the zip file you need for the release? As Travis generates one, it seems like adding something manually is double handling 🤔

**Comment by jdkato** [comment]
Travis will automatically upload it to GitHub after you push a tag, too.

**Comment by ChrisChinchilla** [comment]
@jdkato Do these changes look right? Keen to get the other styles we have up to scratch and want to know if I got things right

**Comment by jdkato** [comment]
This looks good besides the two points below:

1. The [`meta.json`](https://github.com/testthedocs/CockroachDB/blob/master/meta.json)  file needs to be included in the style folder.

2. The `url` entry in this PR needs to be changed from `https://github.com/testthedocs/CockroachDB/archive/master.zip` (the entire repo) to just `https://github.com/testthedocs/CockroachDB/releases/latest/download/CockroachDB.zip` (once the `.zip` is uploaded).

**Comment by ChrisChinchilla** [comment]
@jdkato I really don't understand where you get this latest release link from. I have Travis setup, it's automatically creating release assets, and still all I get is 

https://github.com/testthedocs/CockroachDB/archive/0.1.0.zip etc

And when I look at other repos, that's also all I see, any instructions I can look at? This is confounding me :(

_meta.json_ moved

**Comment by jdkato** [comment]
Is it possible that you haven't set up the `GITHUB_TOKEN` that gives Travis permission to upload the zip?

https://github.com/testthedocs/CockroachDB/blob/8320863e48a077a77ba67110e8398a486f7d0b5e/.travis.yml#L23

**Comment by ChrisChinchilla** [comment]
@jdkato Oh my, I finally got it working. Was a mix of incorrect secret formatting in Travis and some other things

**Comment by jdkato** [comment]
Yes, it looks good. Once the link is updated, I'll merge this and it'll be available in Vale Server.

**Comment by ChrisChinchilla** [comment]
@jdkato link updated… But when I have more of these ready, we'll transfer ownership too and update the links again.

**Pull request merged**
